// flow-typed signature: 2bdd6a27509d174e76967081d5d22a67
// flow-typed version: <<STUB>>/nano-css_v3.5.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nano-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nano-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nano-css/addon/__dev__/warnOnMissingDependencies' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/amp.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/amp.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/atoms.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/atoms.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/atoms.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/atoms.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/emmet/emmet.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/emmet/emmet.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/emmet/emmet.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/emmet/emmet.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/env' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/extract.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/index.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/index.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/jsx.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/jsx.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/jsx.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/jsx.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/keyframes.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/keyframes.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/keyframes.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/keyframes.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/limit.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/nesting.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/prefixer.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/put.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/put.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/put.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/put.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/reset.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/rule.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/rule.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/rule.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/rule.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/setup' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/sheet.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/snake.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/tachyons.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/units.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/units.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/units.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/units.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/validate.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/validate.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/virtual.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/virtual.server.dev.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/virtual.server.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/__tests__/virtual.test' {
  declare module.exports: any;
}

declare module 'nano-css/addon/amp' {
  declare module.exports: any;
}

declare module 'nano-css/addon/animate/fadeIn' {
  declare module.exports: any;
}

declare module 'nano-css/addon/animate/fadeInDown' {
  declare module.exports: any;
}

declare module 'nano-css/addon/animate/fadeInScale' {
  declare module.exports: any;
}

declare module 'nano-css/addon/animate/fadeOut' {
  declare module.exports: any;
}

declare module 'nano-css/addon/animate/fadeOutScale' {
  declare module.exports: any;
}

declare module 'nano-css/addon/array' {
  declare module.exports: any;
}

declare module 'nano-css/addon/atoms' {
  declare module.exports: any;
}

declare module 'nano-css/addon/cache' {
  declare module.exports: any;
}

declare module 'nano-css/addon/component' {
  declare module.exports: any;
}

declare module 'nano-css/addon/cssom' {
  declare module.exports: any;
}

declare module 'nano-css/addon/decorator' {
  declare module.exports: any;
}

declare module 'nano-css/addon/drule' {
  declare module.exports: any;
}

declare module 'nano-css/addon/dsheet' {
  declare module.exports: any;
}

declare module 'nano-css/addon/emmet' {
  declare module.exports: any;
}

declare module 'nano-css/addon/extract' {
  declare module.exports: any;
}

declare module 'nano-css/addon/global' {
  declare module.exports: any;
}

declare module 'nano-css/addon/googleFont' {
  declare module.exports: any;
}

declare module 'nano-css/addon/hydrate' {
  declare module.exports: any;
}

declare module 'nano-css/addon/hyperstyle' {
  declare module.exports: any;
}

declare module 'nano-css/addon/important' {
  declare module.exports: any;
}

declare module 'nano-css/addon/jsx' {
  declare module.exports: any;
}

declare module 'nano-css/addon/keyframes' {
  declare module.exports: any;
}

declare module 'nano-css/addon/limit' {
  declare module.exports: any;
}

declare module 'nano-css/addon/nesting' {
  declare module.exports: any;
}

declare module 'nano-css/addon/pipe' {
  declare module.exports: any;
}

declare module 'nano-css/addon/prefixer' {
  declare module.exports: any;
}

declare module 'nano-css/addon/ref' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset-font' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/EricMeyer' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/EricMeyerCondensed' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/Minimalistic' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/Minimalistic2' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/Minimalistic3' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/Normalize' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/PoorMan' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/ShaunInman' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/Siolon' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/Tantek' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/Tripoli' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/Universal' {
  declare module.exports: any;
}

declare module 'nano-css/addon/reset/Yahoo' {
  declare module.exports: any;
}

declare module 'nano-css/addon/rtl' {
  declare module.exports: any;
}

declare module 'nano-css/addon/rule' {
  declare module.exports: any;
}

declare module 'nano-css/addon/sheet' {
  declare module.exports: any;
}

declare module 'nano-css/addon/snake' {
  declare module.exports: any;
}

declare module 'nano-css/addon/sourcemaps' {
  declare module.exports: any;
}

declare module 'nano-css/addon/spread' {
  declare module.exports: any;
}

declare module 'nano-css/addon/stable' {
  declare module.exports: any;
}

declare module 'nano-css/addon/style' {
  declare module.exports: any;
}

declare module 'nano-css/addon/styled' {
  declare module.exports: any;
}

declare module 'nano-css/addon/stylis' {
  declare module.exports: any;
}

declare module 'nano-css/addon/stylis/plugin-onRule' {
  declare module.exports: any;
}

declare module 'nano-css/addon/tachyons' {
  declare module.exports: any;
}

declare module 'nano-css/addon/unitless' {
  declare module.exports: any;
}

declare module 'nano-css/addon/units' {
  declare module.exports: any;
}

declare module 'nano-css/addon/useStyles' {
  declare module.exports: any;
}

declare module 'nano-css/addon/util/cloneElement' {
  declare module.exports: any;
}

declare module 'nano-css/addon/util/transformComponentDynamic' {
  declare module.exports: any;
}

declare module 'nano-css/addon/util/transformComponentStatic' {
  declare module.exports: any;
}

declare module 'nano-css/addon/validate' {
  declare module.exports: any;
}

declare module 'nano-css/addon/virtual' {
  declare module.exports: any;
}

declare module 'nano-css/addon/withStyles' {
  declare module.exports: any;
}

declare module 'nano-css/preset/react' {
  declare module.exports: any;
}

declare module 'nano-css/preset/sheet' {
  declare module.exports: any;
}

declare module 'nano-css/preset/vdom' {
  declare module.exports: any;
}

declare module 'nano-css/prettier.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nano-css/addon/__dev__/warnOnMissingDependencies.js' {
  declare module.exports: $Exports<'nano-css/addon/__dev__/warnOnMissingDependencies'>;
}
declare module 'nano-css/addon/__tests__/amp.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/amp.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/amp.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/amp.server.test'>;
}
declare module 'nano-css/addon/__tests__/atoms.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/atoms.dev.test'>;
}
declare module 'nano-css/addon/__tests__/atoms.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/atoms.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/atoms.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/atoms.server.test'>;
}
declare module 'nano-css/addon/__tests__/atoms.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/atoms.test'>;
}
declare module 'nano-css/addon/__tests__/emmet/emmet.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/emmet/emmet.dev.test'>;
}
declare module 'nano-css/addon/__tests__/emmet/emmet.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/emmet/emmet.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/emmet/emmet.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/emmet/emmet.server.test'>;
}
declare module 'nano-css/addon/__tests__/emmet/emmet.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/emmet/emmet.test'>;
}
declare module 'nano-css/addon/__tests__/env.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/env'>;
}
declare module 'nano-css/addon/__tests__/extract.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/extract.server.test'>;
}
declare module 'nano-css/addon/__tests__/index.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/index.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/index.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/index.server.test'>;
}
declare module 'nano-css/addon/__tests__/index.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/index.test'>;
}
declare module 'nano-css/addon/__tests__/jsx.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/jsx.dev.test'>;
}
declare module 'nano-css/addon/__tests__/jsx.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/jsx.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/jsx.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/jsx.server.test'>;
}
declare module 'nano-css/addon/__tests__/jsx.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/jsx.test'>;
}
declare module 'nano-css/addon/__tests__/keyframes.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/keyframes.dev.test'>;
}
declare module 'nano-css/addon/__tests__/keyframes.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/keyframes.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/keyframes.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/keyframes.server.test'>;
}
declare module 'nano-css/addon/__tests__/keyframes.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/keyframes.test'>;
}
declare module 'nano-css/addon/__tests__/limit.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/limit.server.test'>;
}
declare module 'nano-css/addon/__tests__/nesting.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/nesting.test'>;
}
declare module 'nano-css/addon/__tests__/prefixer.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/prefixer.test'>;
}
declare module 'nano-css/addon/__tests__/put.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/put.dev.test'>;
}
declare module 'nano-css/addon/__tests__/put.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/put.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/put.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/put.server.test'>;
}
declare module 'nano-css/addon/__tests__/put.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/put.test'>;
}
declare module 'nano-css/addon/__tests__/reset.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/reset.test'>;
}
declare module 'nano-css/addon/__tests__/rule.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/rule.dev.test'>;
}
declare module 'nano-css/addon/__tests__/rule.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/rule.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/rule.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/rule.server.test'>;
}
declare module 'nano-css/addon/__tests__/rule.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/rule.test'>;
}
declare module 'nano-css/addon/__tests__/setup.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/setup'>;
}
declare module 'nano-css/addon/__tests__/sheet.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/sheet.test'>;
}
declare module 'nano-css/addon/__tests__/snake.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/snake.test'>;
}
declare module 'nano-css/addon/__tests__/tachyons.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/tachyons.test'>;
}
declare module 'nano-css/addon/__tests__/units.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/units.dev.test'>;
}
declare module 'nano-css/addon/__tests__/units.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/units.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/units.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/units.server.test'>;
}
declare module 'nano-css/addon/__tests__/units.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/units.test'>;
}
declare module 'nano-css/addon/__tests__/validate.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/validate.dev.test'>;
}
declare module 'nano-css/addon/__tests__/validate.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/validate.test'>;
}
declare module 'nano-css/addon/__tests__/virtual.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/virtual.dev.test'>;
}
declare module 'nano-css/addon/__tests__/virtual.server.dev.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/virtual.server.dev.test'>;
}
declare module 'nano-css/addon/__tests__/virtual.server.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/virtual.server.test'>;
}
declare module 'nano-css/addon/__tests__/virtual.test.js' {
  declare module.exports: $Exports<'nano-css/addon/__tests__/virtual.test'>;
}
declare module 'nano-css/addon/amp.js' {
  declare module.exports: $Exports<'nano-css/addon/amp'>;
}
declare module 'nano-css/addon/animate/fadeIn.js' {
  declare module.exports: $Exports<'nano-css/addon/animate/fadeIn'>;
}
declare module 'nano-css/addon/animate/fadeInDown.js' {
  declare module.exports: $Exports<'nano-css/addon/animate/fadeInDown'>;
}
declare module 'nano-css/addon/animate/fadeInScale.js' {
  declare module.exports: $Exports<'nano-css/addon/animate/fadeInScale'>;
}
declare module 'nano-css/addon/animate/fadeOut.js' {
  declare module.exports: $Exports<'nano-css/addon/animate/fadeOut'>;
}
declare module 'nano-css/addon/animate/fadeOutScale.js' {
  declare module.exports: $Exports<'nano-css/addon/animate/fadeOutScale'>;
}
declare module 'nano-css/addon/array.js' {
  declare module.exports: $Exports<'nano-css/addon/array'>;
}
declare module 'nano-css/addon/atoms.js' {
  declare module.exports: $Exports<'nano-css/addon/atoms'>;
}
declare module 'nano-css/addon/cache.js' {
  declare module.exports: $Exports<'nano-css/addon/cache'>;
}
declare module 'nano-css/addon/component.js' {
  declare module.exports: $Exports<'nano-css/addon/component'>;
}
declare module 'nano-css/addon/cssom.js' {
  declare module.exports: $Exports<'nano-css/addon/cssom'>;
}
declare module 'nano-css/addon/decorator.js' {
  declare module.exports: $Exports<'nano-css/addon/decorator'>;
}
declare module 'nano-css/addon/drule.js' {
  declare module.exports: $Exports<'nano-css/addon/drule'>;
}
declare module 'nano-css/addon/dsheet.js' {
  declare module.exports: $Exports<'nano-css/addon/dsheet'>;
}
declare module 'nano-css/addon/emmet.js' {
  declare module.exports: $Exports<'nano-css/addon/emmet'>;
}
declare module 'nano-css/addon/extract.js' {
  declare module.exports: $Exports<'nano-css/addon/extract'>;
}
declare module 'nano-css/addon/global.js' {
  declare module.exports: $Exports<'nano-css/addon/global'>;
}
declare module 'nano-css/addon/googleFont.js' {
  declare module.exports: $Exports<'nano-css/addon/googleFont'>;
}
declare module 'nano-css/addon/hydrate.js' {
  declare module.exports: $Exports<'nano-css/addon/hydrate'>;
}
declare module 'nano-css/addon/hyperstyle.js' {
  declare module.exports: $Exports<'nano-css/addon/hyperstyle'>;
}
declare module 'nano-css/addon/important.js' {
  declare module.exports: $Exports<'nano-css/addon/important'>;
}
declare module 'nano-css/addon/jsx.js' {
  declare module.exports: $Exports<'nano-css/addon/jsx'>;
}
declare module 'nano-css/addon/keyframes.js' {
  declare module.exports: $Exports<'nano-css/addon/keyframes'>;
}
declare module 'nano-css/addon/limit.js' {
  declare module.exports: $Exports<'nano-css/addon/limit'>;
}
declare module 'nano-css/addon/nesting.js' {
  declare module.exports: $Exports<'nano-css/addon/nesting'>;
}
declare module 'nano-css/addon/pipe.js' {
  declare module.exports: $Exports<'nano-css/addon/pipe'>;
}
declare module 'nano-css/addon/prefixer.js' {
  declare module.exports: $Exports<'nano-css/addon/prefixer'>;
}
declare module 'nano-css/addon/ref.js' {
  declare module.exports: $Exports<'nano-css/addon/ref'>;
}
declare module 'nano-css/addon/reset-font.js' {
  declare module.exports: $Exports<'nano-css/addon/reset-font'>;
}
declare module 'nano-css/addon/reset/EricMeyer.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/EricMeyer'>;
}
declare module 'nano-css/addon/reset/EricMeyerCondensed.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/EricMeyerCondensed'>;
}
declare module 'nano-css/addon/reset/Minimalistic.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/Minimalistic'>;
}
declare module 'nano-css/addon/reset/Minimalistic2.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/Minimalistic2'>;
}
declare module 'nano-css/addon/reset/Minimalistic3.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/Minimalistic3'>;
}
declare module 'nano-css/addon/reset/Normalize.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/Normalize'>;
}
declare module 'nano-css/addon/reset/PoorMan.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/PoorMan'>;
}
declare module 'nano-css/addon/reset/ShaunInman.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/ShaunInman'>;
}
declare module 'nano-css/addon/reset/Siolon.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/Siolon'>;
}
declare module 'nano-css/addon/reset/Tantek.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/Tantek'>;
}
declare module 'nano-css/addon/reset/Tripoli.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/Tripoli'>;
}
declare module 'nano-css/addon/reset/Universal.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/Universal'>;
}
declare module 'nano-css/addon/reset/Yahoo.js' {
  declare module.exports: $Exports<'nano-css/addon/reset/Yahoo'>;
}
declare module 'nano-css/addon/rtl.js' {
  declare module.exports: $Exports<'nano-css/addon/rtl'>;
}
declare module 'nano-css/addon/rule.js' {
  declare module.exports: $Exports<'nano-css/addon/rule'>;
}
declare module 'nano-css/addon/sheet.js' {
  declare module.exports: $Exports<'nano-css/addon/sheet'>;
}
declare module 'nano-css/addon/snake.js' {
  declare module.exports: $Exports<'nano-css/addon/snake'>;
}
declare module 'nano-css/addon/sourcemaps.js' {
  declare module.exports: $Exports<'nano-css/addon/sourcemaps'>;
}
declare module 'nano-css/addon/spread.js' {
  declare module.exports: $Exports<'nano-css/addon/spread'>;
}
declare module 'nano-css/addon/stable.js' {
  declare module.exports: $Exports<'nano-css/addon/stable'>;
}
declare module 'nano-css/addon/style.js' {
  declare module.exports: $Exports<'nano-css/addon/style'>;
}
declare module 'nano-css/addon/styled.js' {
  declare module.exports: $Exports<'nano-css/addon/styled'>;
}
declare module 'nano-css/addon/stylis.js' {
  declare module.exports: $Exports<'nano-css/addon/stylis'>;
}
declare module 'nano-css/addon/stylis/plugin-onRule.js' {
  declare module.exports: $Exports<'nano-css/addon/stylis/plugin-onRule'>;
}
declare module 'nano-css/addon/tachyons.js' {
  declare module.exports: $Exports<'nano-css/addon/tachyons'>;
}
declare module 'nano-css/addon/unitless.js' {
  declare module.exports: $Exports<'nano-css/addon/unitless'>;
}
declare module 'nano-css/addon/units.js' {
  declare module.exports: $Exports<'nano-css/addon/units'>;
}
declare module 'nano-css/addon/useStyles.js' {
  declare module.exports: $Exports<'nano-css/addon/useStyles'>;
}
declare module 'nano-css/addon/util/cloneElement.js' {
  declare module.exports: $Exports<'nano-css/addon/util/cloneElement'>;
}
declare module 'nano-css/addon/util/transformComponentDynamic.js' {
  declare module.exports: $Exports<'nano-css/addon/util/transformComponentDynamic'>;
}
declare module 'nano-css/addon/util/transformComponentStatic.js' {
  declare module.exports: $Exports<'nano-css/addon/util/transformComponentStatic'>;
}
declare module 'nano-css/addon/validate.js' {
  declare module.exports: $Exports<'nano-css/addon/validate'>;
}
declare module 'nano-css/addon/virtual.js' {
  declare module.exports: $Exports<'nano-css/addon/virtual'>;
}
declare module 'nano-css/addon/withStyles.js' {
  declare module.exports: $Exports<'nano-css/addon/withStyles'>;
}
declare module 'nano-css/index' {
  declare module.exports: $Exports<'nano-css'>;
}
declare module 'nano-css/index.js' {
  declare module.exports: $Exports<'nano-css'>;
}
declare module 'nano-css/preset/react.js' {
  declare module.exports: $Exports<'nano-css/preset/react'>;
}
declare module 'nano-css/preset/sheet.js' {
  declare module.exports: $Exports<'nano-css/preset/sheet'>;
}
declare module 'nano-css/preset/vdom.js' {
  declare module.exports: $Exports<'nano-css/preset/vdom'>;
}
declare module 'nano-css/prettier.config.js' {
  declare module.exports: $Exports<'nano-css/prettier.config'>;
}
