// flow-typed signature: 6ed57e281e9ba15c32582ffc22efd32c
// flow-typed version: <<STUB>>/@storybook/addon-storyshots-puppeteer_v4.1.4/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-storyshots-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-storyshots-puppeteer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-storyshots-puppeteer/dist/__tests__/url.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots-puppeteer/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots-puppeteer/dist/url' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots-puppeteer/src/__tests__/url.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots-puppeteer/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots-puppeteer/src/url' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-storyshots-puppeteer/dist/__tests__/url.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots-puppeteer/dist/__tests__/url.test'>;
}
declare module '@storybook/addon-storyshots-puppeteer/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots-puppeteer/dist/index'>;
}
declare module '@storybook/addon-storyshots-puppeteer/dist/url.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots-puppeteer/dist/url'>;
}
declare module '@storybook/addon-storyshots-puppeteer/src/__tests__/url.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots-puppeteer/src/__tests__/url.test'>;
}
declare module '@storybook/addon-storyshots-puppeteer/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots-puppeteer/src/index'>;
}
declare module '@storybook/addon-storyshots-puppeteer/src/url.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots-puppeteer/src/url'>;
}
